In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('dataset.csv')

In [3]:
df.head(10)

Unnamed: 0  Age     Sex  Job Housing Saving accounts Checking account  \
0           0   67    male    2     own             NaN           little   
1           1   22  female    2     own          little         moderate   
2           2   49    male    1     own          little              NaN   
3           3   45    male    2    free          little           little   
4           4   53    male    2    free          little           little   
5           5   35    male    1    free             NaN              NaN   
6           6   53    male    2     own      quite rich              NaN   
7           7   35    male    3    rent          little         moderate   
8           8   61    male    1     own            rich              NaN   
9           9   28    male    3     own          little         moderate   

   Credit amount  Duration              Purpose  Risk  card number  
0           1169         6             radio/TV  good         9999  
1           5951        48             radio/TV   bad         1000  
2           2096        12            education  good         1001  
3           7882        42  furniture/equipment  good         1002  
4           4870        24                  car   bad         1003  
5           9055        36            education  good         1004  
6           2835        24  furniture/equipment  good         1005  
7           6948        36                  car  good         1006  
8           3059        12             radio/TV  good         1007  
9           5234        30                  car   bad         1008

In [4]:
df = df.drop(['Unnamed: 0'], axis = 1)  

In [5]:
df = df.drop(['Sex'], axis = 1)

In [6]:
df.head()

Age  Job Housing Saving accounts Checking account  Credit amount  Duration  \
0   67    2     own             NaN           little           1169         6   
1   22    2     own          little         moderate           5951        48   
2   49    1     own          little              NaN           2096        12   
3   45    2    free          little           little           7882        42   
4   53    2    free          little           little           4870        24   

               Purpose  Risk  card number  
0             radio/TV  good         9999  
1             radio/TV   bad         1000  
2            education  good         1001  
3  furniture/equipment  good         1002  
4                  car   bad         1003

In [7]:
df.shape

(1000, 10)

In [8]:
df.isnull().sum()

Age                   0
Job                   0
Housing               0
Saving accounts     183
Checking account    394
Credit amount         0
Duration              0
Purpose               0
Risk                  0
card number           0
dtype: int64

In [9]:
df.dtypes

Age                  int64
Job                  int64
Housing             object
Saving accounts     object
Checking account    object
Credit amount        int64
Duration             int64
Purpose             object
Risk                object
card number          int64
dtype: object

In [10]:
print(df.groupby('Housing').size())
print('\n',df.groupby('Saving accounts').size())
print('\n',df.groupby('Checking account').size())
print('\n',df.groupby('Purpose').size())
print('\n',df.groupby('Risk').size())

Housing
free    108
own     713
rent    179
dtype: int64

 Saving accounts
little        603
moderate      103
quite rich     63
rich           48
dtype: int64

 Checking account
little      274
moderate    269
rich         63
dtype: int64

 Purpose
business                97
car                    337
domestic appliances     12
education               59
furniture/equipment    181
radio/TV               280
repairs                 22
vacation/others         12
dtype: int64

 Risk
bad     300
good    700
dtype: int64


In [11]:
df['Saving accounts'].fillna('little', inplace = True)

In [12]:
df['Checking account'].fillna('little', inplace = True)

In [13]:
df.isnull().sum()

Age                 0
Job                 0
Housing             0
Saving accounts     0
Checking account    0
Credit amount       0
Duration            0
Purpose             0
Risk                0
card number         0
dtype: int64

In [14]:





df.head()

Age  Job Housing Saving accounts Checking account  Credit amount  Duration  \
0   67    2     own          little           little           1169         6   
1   22    2     own          little         moderate           5951        48   
2   49    1     own          little           little           2096        12   
3   45    2    free          little           little           7882        42   
4   53    2    free          little           little           4870        24   

               Purpose  Risk  card number  
0             radio/TV  good         9999  
1             radio/TV   bad         1000  
2            education  good         1001  
3  furniture/equipment  good         1002  
4                  car   bad         1003

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [16]:
df['Housing'] = le.fit_transform(df['Housing'])
df['Saving accounts'] = le.fit_transform(df['Saving accounts'])
df['Checking account'] = le.fit_transform(df['Checking account'])
df['Purpose'] = le.fit_transform(df['Purpose'])
df['Risk'] = le.fit_transform(df['Risk'])

In [17]:
df.head()

Age  Job  Housing  Saving accounts  Checking account  Credit amount  \
0   67    2        1                0                 0           1169   
1   22    2        1                0                 1           5951   
2   49    1        1                0                 0           2096   
3   45    2        0                0                 0           7882   
4   53    2        0                0                 0           4870   

   Duration  Purpose  Risk  card number  
0         6        5     1         9999  
1        48        5     0         1000  
2        12        3     1         1001  
3        42        4     1         1002  
4        24        1     0         1003

In [18]:
X=df.drop('Risk',axis=1)
Y=df['Risk']

In [19]:
X.values

array([[  67,    2,    1, ...,    6,    5, 9999],
       [  22,    2,    1, ...,   48,    5, 1000],
       [  49,    1,    1, ...,   12,    3, 1001],
       ...,
       [  38,    2,    1, ...,   12,    5, 1996],
       [  23,    2,    0, ...,   45,    5, 1997],
       [  27,    2,    1, ...,   45,    1, 1998]], dtype=int64)

In [20]:
Y.values

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X.values,Y.values,test_size = 0.50,random_state = 1)

In [22]:
from sklearn.svm import SVC

In [23]:
sv=SVC(kernel='linear')
sv.fit(X_train,Y_train)
y_pred=sv.predict(X_test)

In [24]:

y_pred

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [25]:
sv.predict([[67,2,1,0,0,1169,6,5]])

ValueError: X.shape[1] = 8 should be equal to 9, the number of features at training time

In [ ]:
sv.predict([[67,2,1,0,0,1169,6,5]])

In [ ]:
sv.predict([[67,2,1,0,0,1169,6,5]])

In [52]:
Y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,

In [53]:
from sklearn.metrics import accuracy_score

In [54]:
accuracy=accuracy_score(Y_test,y_pred)


In [42]:
print(accuracy)

0.684
